// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://afglpoufxxgdxylvgeex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmZ2xwb3VmeHhnZHh5bHZnZWV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNDc3ODQsImV4cCI6MjA2OTYyMzc4NH0.zS-liSt8emGixeRJUTDgl7RR0767fcNSlzDPC8kzUUs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});